apiVersion: v1
appVersion: V1.0
description: 'Het Basis Registratie Personen Component is een implementatie van de door Haal Centraal ontwikkelde API-specificatie in de vorm van een Common Ground container. Dat betekent dat het ten opzichte van die referentie een aantal extra opties kent (zoals extended en filteren van data). Dit Common Ground component kan op twee manieren worden ingezet. Om te beginnen kan het aan de achterkant worden voorzien van datafixtures in de vorm van een Excel sheet. Op deze manier kan er een “specifieke” mock worden gecreëerd voor het testen van applicaties (al dan niet in combinatie met Digispoof). Het is echter ook mogelijke om het BRP Component in te zetten in samenhang met het StuF Component, in dat geval worden API-verzoeken op het BRP vertaald naar StuF berichten op GBA of GBAV aansluiting en levert het component daadwerkelijk een BRP koppeling.'
name: brpservice
version: 0.1.0
home: https://www.conduction.nl
icon: https://conductionnl.github.io/images/conduction_avatar_blue_on_transparant.svg
sources:
    - https://commonground.conduction.nl/
    - https://www.commonground.nl/
keywords:
    - commonground
    - haven
    - nlx
    - component
maintainers:
    - email: ruben@conduction.nl
      name: Ruben van der Linde
    - email: info@conduction.nl
      name: Conduction
dependencies:
    - name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.1.1
      condition: postgresql.enabled
    - name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 12.7.7
      condition: redis.enabled