apiVersion: v1
kind: Secret
metadata:
    name: {{ template "fullname" . }}-certificate
    labels:
        app.kubernetes.io/name: {{ .Values.settings.name }}
        app.kubernetes.io/part-of: {{ .Values.settings.name }}
        helm.sh/chart: {{ include "chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
type: kubernetes.io/tls
data:
    tls.crt: {{ .Values.security.certificate | quote }}
    tls.key: {{ .Values.security.privateKey | quote }}
